controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    jointX_position_controller:
      type: position_controllers/JointGroupPositionController

    jointX_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    jointX_effort_controller:
      type: effort_controllers/JointGroupEffortController

    jointYZ0_position_controller:
      type: position_controllers/JointGroupPositionController

    jointYZ0_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    jointYZ0_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    jointYZ1_position_controller:
      type: position_controllers/JointGroupPositionController

    jointYZ1_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    jointYZ1_effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    group_position_controller:
      type: position_controllers/JointGroupPositionController

    group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    group_effort_controller:
      type: effort_controllers/JointGroupEffortController

jointX_position_controller:
  ros__parameters:
    joints:
      - jointX

jointX_velocity_controller:
  ros__parameters:
    joints:
      - jointX

jointX_effort_controller:
  ros__parameters:
    joints:
      - jointX

jointYZ0_position_controller:
  ros__parameters:
    joints:
      - jointYZ0

jointYZ0_velocity_controller:
  ros__parameters:
    joints:
      - jointYZ0

jointYZ0_effort_controller:
  ros__parameters:
    joints:
      - jointYZ0

jointYZ1_position_controller:
  ros__parameters:
    joints:
      - jointYZ1

jointYZ1_velocity_controller:
  ros__parameters:
    joints:
      - jointYZ1

jointYZ1_effort_controller:
  ros__parameters:
    joints:
      - jointYZ1

group_position_controller:
  ros__parameters:
    joints:
      - jointYZ0
      - jointYZ1

group_velocity_controller:
  ros__parameters:
    joints:
      - jointYZ0
      - jointYZ1

group_effort_controller:
  ros__parameters:
    joints:
      - jointYZ0
      - jointYZ1
