controller_manager:
  ros__parameters:
    update_rate: 80  # Hz
    manipulator_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joystick_position_controller:
      type: position_controllers/JointGroupPositionController
    x_joint_comp_position_controller:
      type: position_controllers/JointGroupPositionController
    joint_state_controller:
      type: joint_state_controller/JointStateController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# parameters for each controller listed under controller manager
manipulator_joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - x_joint_plan
      - y_joint
      - z_joint
      - a_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

x_joint_comp_position_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - x_joint_comp

joystick_position_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - x_joint_plan
      - y_joint
      - z_joint
      - a_joint
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
