controller_manager:
  ros__parameters:
    update_rate: 600  # Hz
    joystick_position_controller:
      type: position_controllers/JointGroupPositionController
    joint_state_controller:
      type: joint_state_controller/JointStateController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joystick_position_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - x_joint_plan
      - y_joint
      - z_joint
      - a_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
